version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
    expose:
      - "5252" # Open port 5252 "internally for communication with other containers"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/var/www/html
    container_name: front-end
    expose:
      - "9000" # Open port 9000 ""

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy-image
    ports:
      - "80:80" # Map container's port 80
    depends_on:
      - back-end
      - front-end
      